name: C++ Coverage

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo apt install gcovr curl
        wget -O cc-reporter https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
        chmod +x ./cc-reporter
        ./cc-reporter before-build

    - name: build & test
      run: |
        mkdir coverage
        mkdir build
        cd build
        cmake ..
        make
        make test
        make gcov
        cd ..

    - name: publish code coverage to code climate
      env:
        CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      if: ${{ github.ref == 'refs/heads/main' }}
      run: |
        ./cc-reporter format-coverage build/coverage -t gcov -p $(basename $PWD)
        ./cc-reporter upload-coverage -r "$CC_TEST_REPORTER_ID" -i coverage/codeclimate.json
