name: C++ Checks

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: sudo apt install clang-format clang-tidy cppcheck flake8

    - name: format
      run: clang-format src/*.cpp test/*.cpp -i --style=Google

    - name: clang-tidy
      if: always()
      run: clang-tidy --export-fixes=clang_tidy_output.yml -header-filter=.* -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-* src/*.cpp -- -Iincludes/

    - name: cppcheck
      if: always()
      run: cppcheck --enable=all --suppress=missingIncludeSystem --suppress=unusedFunction src/*.cpp