name: Pre Commit Checks

on:
  push:
    branches:
    - main
  pull_request:

env:
  CC_BINARY: https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: |
        sudo apt install gcovr curl
        wget -O cc-reporter ${{ env.CC_BINARY }}
        chmod +x ./cc-reporter
        python3 -m pip install -r requirements.txt
        pre-commit autoupdate
        pre-commit install
        ./cc-reporter before-build

    - name: build & test
      run: |
        mkdir coverage
        mkdir build
        cd build
        cmake ..
        make
        make test
        make gcov
        cd ..

    - name: Run pre-commit tests
      run: |
        pre-commit run --all-files
