name: C++ Checks

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-20.04
    steps:
    - name: checkout code
      uses: actions/checkout@v3

    - name: install dependencies
      run: |
        python3 -m pip install -r requirements.txt
        pre-commit autoupdate
        pre-commit install

    - name: Run pre-commit tests
      run: |
        pre-commit run --all-files
